### ISSUE TITLE
初始化InfluxDB连接时添加创建数据库

### ISSUE THREAD

**Issue by Gahon1995** [brains-platform/spring-boot-starter-influxdb#2]
在返回`influxDB`添加 `influxDB.query(new Query("CREATE DATABASE "+properties.getDatabase(), properties.getDatabase()));`， 这样才能够保证在查询或者添加到新表的时候不会报错。

**Comment by dagmom** [comment]
不太合适操作的账号不一定有创建权限，可以增加特性，是否自动建库，不过这可能不是大多数场景需要的，一般库会有DBA管理
